### ISSUE TITLE
"invalid date" when trying to download into db

### ISSUE THREAD

**Issue by ciryon** [alexvollmer/itunes-connect#1]
I am able to download successfully for daily or weekly reports, but when I attempt to save into db using the -b flag it fails with an "invalid date" message.

Example command that I used:

itunes_connect download -d 05/30/2010 -b /tmp/data.sqlite

I am using Mac OS X and UK region format (which means that the above date in my system is 30/05/2010 if that would matter).

**Comment by alexvollmer** [comment]
Can you try running the command again with the -v and -g flags. It will spew a bunch of output which might be helpful. I haven't used this in a while so it's possible that the website changed and the code doesn't match it.

**Comment by ciryon** [comment]
[22:25][ciryon@Celebros:~]$ itunes_connect download -b /tmp/data.sqlite -v -g
Querying https://itts.apple.com/cgi-bin/WebObjects/Piano.woa with nil
https://itts.apple.com/cgi-bin/WebObjects/Piano.woa -> /var/folders/1y/1yL8y3qAGKC3Ed7onjoWdk+++TI/-Tmp-/e2fe58f4cca8896fd9352dd6479b4c5a.html
Querying /cgi-bin/WebObjects/Piano.woa/8/wo/AGj5kFBzajStQozg27PW4g/0.4 with {"1.Continue.x"=>"36", "1.Continue.y"=>"17", "theAccountPW"=>"zzzxxxyyy", "theAuxValue"=>"", "theAccountName"=>"xxxyyy@zzz.com"}
https://itts.apple.com/cgi-bin/WebObjects/Piano.woa/8/wo/EGj5kFAzajStQozg27PW4g/0.4 -> /var/folders/1y/1yL8y3qPGKC3Dd7onjoWdk+++TI/-Tmp-/f8ad2acdcf4763e7488b723c01c9ac1f.html
Querying /cgi-bin/WebObjects/Piano.woa/8/wo/EGj5kFAzajStWozg27PW4g/2.17 with {"17.9"=>"Summary", "hiddenDayOrWeekSelection"=>"Daily", "17.11"=>"Daily", "hiddenSubmitTypeName"=>"ShowDropDown"}
https://itts.apple.com/cgi-bin/WebObjects/Piano.woa/8/wo/EGj5kFBzajStQozg27PW4g/2.17 -> /var/folders/1y/EGj5kFBzajStQozg27PW4g +++TI/-Tmp-/EGj5kFBzajStQozg27PW4g.html
Querying /cgi-bin/WebObjects/Piano.woa/8/wo/EGj5kFBzajStQozg27PW4g/3.17 with {"download"=>"Download", "17.13.1"=>"06/01/2010", "17.9"=>"Summary", "hiddenDayOrWeekSelection"=>"06/01/2010", "17.11"=>"Daily", "hiddenSubmitTypeName"=>"Download"}
https://itts.apple.com/cgi-bin/WebObjects/Piano.woa/8/wo/EGj5kFBzajStQozg27PW4g/3.17 -> /var/folders/1y/EGj5kFBzajStQozg27PW4g +++TI/-Tmp-/EGj5kFBzajStQozg27PW4g.html
Importing into database file: /tmp/data.sqlite
invalid date
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/date.rb:956:in `new_by_frags'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/date.rb:1000:in`parse'
/Library/Ruby/Gems/1.8/gems/itunes-connect-0.9.0/lib/itunes_connect/report.rb:25:in `initialize'
/Library/Ruby/Gems/1.8/gems/itunes-connect-0.9.0/lib/itunes_connect/report.rb:19:in`each'
/Library/Ruby/Gems/1.8/gems/itunes-connect-0.9.0/lib/itunes_connect/report.rb:19:in `initialize'
/Library/Ruby/Gems/1.8/gems/itunes-connect-0.9.0/lib/itunes_connect/commands/download.rb:57:in`new'
/Library/Ruby/Gems/1.8/gems/itunes-connect-0.9.0/lib/itunes_connect/commands/download.rb:57:in `execute!'
/Library/Ruby/Gems/1.8/gems/itunes-connect-0.9.0/bin/itunes_connect:19
/usr/bin/itunes_connect:19:in`load'
/usr/bin/itunes_connect:19

(private data scrambled)

**Comment by alexvollmer** [comment]
Thanks for posting that. It looks like the code is choking on parsing some date-format (perhaps some localization assumption I made). Is it possible to grab the report by hand and post the first few lines of it?

Thanks!

**Comment by ciryon** [comment]
Here's the report:

Provider    Provider Country    Vendor Identifier   UPC ISRC    Artist / Show   Title / Episode / Season    Label/Studio/Network    Product Type Identifier Units   Royalty Price   Begin Date  End Date    Customer Currency   Country Code    Royalty Currency    Preorder    Season Pass ISAN    Apple Identifier    Customer Price  CMA Asset/Content Flavor    Vendor Offer Code   Grid    Promo Code  Parent Identifier
APPLE   US  1001            MyCompany   MyApp       1   1   .97 06/01/2010  06/01/2010  EUR FR  EUR         123456789   1.59  
APPLE   US  1001            MyCompany   MyApp       1   4   1.4 06/01/2010  06/01/2010  USD US  USD         123456789   1.99  
APPLE   US  1001            MyCompany   MyApp       1   1   .72 06/01/2010  06/01/2010  GBP GB  GBP         123456789   1.19  
APPLE   US  1001            MyCompany   MyApp       1   2   .97 06/01/2010  06/01/2010  SEK SE  EUR         123456789   15

**Comment by alexvollmer** [comment]
Thanks for sending this. I took this report and ran some tests on it and can't reproduce the problem you're having. So I've added some extra instrumentation on a branch that will capture the original input as well as dump a backtrace out. Checkout the 'av/issue-1' branch and install the gem from there via rake. If you have any questions about building the gem from the project source, let me know.

Cheers,

Alex

**Comment by ciryon** [comment]
Sorry for the delay, here's the output:

[08:41][ciryon@Celebros]$ itunes_connect download -d 06/06/2010 -b /tmp/data.sqlite -v -g 
Querying https://itts.apple.com/cgi-bin/WebObjects/Piano.woa with nil
https://itts.apple.com/cgi-bin/WebObjects/Piano.woa -> /var/folders/1y/1yL8y3qPGKC2Dd7onjoWdk+++TI/-Tmp-/642015b051a921fed95668dc80f43493.html
Querying /cgi-bin/WebObjects/Piano.woa/13/wo/uAFdDapNvbbpnaMngOu37g/0.4 with {"1.Continue.x"=>"36", "1.Continue.y"=>"17", "theAccountPW"=>"xxxyyy", "theAuxValue"=>"", "theAccountName"=>"xxxyyy@zzz.com"}
https://itts.apple.com/cgi-bin/WebObjects/Piano.woa/13/wo/uAFdDapNvbbpnaMngOu37g/0.4 -> /var/folders/1y/1yL8y3qPGKC3Dd7onjoWdk+++TI/-Tmp-/6fbbb013371581379d1c29b707810cd0.html
Querying /cgi-bin/WebObjects/Piano.woa/13/wo/uAFdDapNvbbpnaMngOu37g/2.17 with {"17.9"=>"Summary", "hiddenDayOrWeekSelection"=>"Daily", "17.11"=>"Daily", "hiddenSubmitTypeName"=>"ShowDropDown"}
https://itts.apple.com/cgi-bin/WebObjects/Piano.woa/13/wo/uAFdDapNvbbpnaMngOu37g/2.17 -> /var/folders/1y/1yL8y3qPGKC3Dd7onjoWdk+++TI/-Tmp-/d4b0735824f607cb9a1e67e20c92277c.html
Querying /cgi-bin/WebObjects/Piano.woa/13/wo/uAFdDapNvbapnaMngOu37g/3.17 with {"download"=>"Download", "17.13.1"=>"06/06/2010", "17.9"=>"Summary", "hiddenDayOrWeekSelection"=>"06/06/2010", "17.11"=>"Daily", "hiddenSubmitTypeName"=>"Download"}
https://itts.apple.com/cgi-bin/WebObjects/Piano.woa/13/wo/uAFdDapNabbpnaMngOu37g/3.17 -> /var/folders/1y/1yL8y3qPGKC2Dd7onjoWdk+++TI/-Tmp-/6d7f7cab8f2c8744ab03c871de5d1d6f.html
Importing into database file: /tmp/data.sqlite
ERROR: invalid date
Saved input to /var/folders/1y/1yL8y3qPGKC3Dd7onjoWdk+++TI/-Tmp-/itunes-connect-20100609-000000
invalid date
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/date.rb:956:in `new_by_frags'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/date.rb:1000:in`parse'
/Library/Ruby/Gems/1.8/gems/itunes-connect-0.9.0/lib/itunes_connect/report.rb:27:in `initialize'
/Library/Ruby/Gems/1.8/gems/itunes-connect-0.9.0/lib/itunes_connect/report.rb:21:in`each'
/Library/Ruby/Gems/1.8/gems/itunes-connect-0.9.0/lib/itunes_connect/report.rb:21:in `initialize'
/Library/Ruby/Gems/1.8/gems/itunes-connect-0.9.0/lib/itunes_connect/commands/download.rb:57:in`new'
/Library/Ruby/Gems/1.8/gems/itunes-connect-0.9.0/lib/itunes_connect/commands/download.rb:57:in `execute!'
/Library/Ruby/Gems/1.8/gems/itunes-connect-0.9.0/bin/itunes_connect:19
/usr/bin/itunes_connect:19:in`load'
/usr/bin/itunes_connect:19

**Comment by alexvollmer** [comment]
Thanks for the reply, but I need the output of the log file. I know it's buried in the console output so you probably missed it. Look for a section like this:

<pre>
Importing into database file: /tmp/data.sqlite
ERROR: invalid date
Saved input to /var/folders/1y/1yL8y3qPGKC3Dd7onjoWdk+++TI/-Tmp-/itunes-connect-20100609-000000
invalid date
</pre>


Send me the contents of that log file. Hopefully we can get to the bottom of this.

**Comment by ciryon** [comment]
Oh, right. Here's the log file output: 

ERROR
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/date.rb:956:in `new_by_frags'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/date.rb:1000:in`parse'
/Library/Ruby/Gems/1.8/gems/itunes-connect-0.9.0/lib/itunes_connect/report.rb:27:in `initialize'
/Library/Ruby/Gems/1.8/gems/itunes-connect-0.9.0/lib/itunes_connect/report.rb:21:in`each'
/Library/Ruby/Gems/1.8/gems/itunes-connect-0.9.0/lib/itunes_connect/report.rb:21:in `initialize'
/Library/Ruby/Gems/1.8/gems/itunes-connect-0.9.0/lib/itunes_connect/commands/download.rb:57:in`new'
/Library/Ruby/Gems/1.8/gems/itunes-connect-0.9.0/lib/itunes_connect/commands/download.rb:57:in `execute!'
/Library/Ruby/Gems/1.8/gems/itunes-connect-0.9.0/bin/itunes_connect:19
/usr/bin/itunes_connect:19:in`load'
/usr/bin/itunes_connect:19

Provider    Provider Country    Vendor Identifier   UPC ISRC    Artist / Show   Title / Episode / Season    Label/Studio/Network    Product Type Identifier Units   Royalty Price   Begin Date  End Date    Customer Currency   Country Code    Royalty Currency    Preorder    Season Pass ISAN    Apple Identifier    Customer Price  CMA Asset/Content Flavor    Vendor Offer Code   Grid    Promo Code  Parent Identifier
APPLE   US  1001            MyCompany   MyApp       1   1   1.4 06/13/2010  06/13/2010  USD US  USD             313954396   1.99  
APPLE   US  1001            MyCompany   MyApp       1   2   .97 06/13/2010  06/13/2010  SEK SE  EUR             313954396   15

**Comment by alexvollmer** [comment]
I'm so sorry for the late response. I was off at WWDC then lost track of stuff. Anyway, I finally got a chance to look at the attached report and I can't get it to fail. I'm completely stumped as to what the problem is. At this point I can only think that there is some local difference. I've pushed one more patch that dumps the environment out to the same log file. If you haven't totally lost patience, give it a try.

**Comment by ciryon** [comment]
Still got this annoying error so I thought I'd bring it up again. :)

It could be that there are local differences since I'm connecting to the Swedish version of iTunes Connect, although I've never seen anything that's localized. 

There is one obvious error that I found while debugging though. In the report.db's initialize function there is a split up into tokens. One of our apps has a space in the name, and that causes problems.
- "token 0: APPLE"
- "token 1: US"
- "token 2: 2001"
- "token 3: Our Company Name"
- "token 4: Our App Name"
- "token 5: With a Space"
- "token 6: 1.1"
- "token 7: 1T"
- "token 8: 1"
- "token 9: 0"
- "token 10: 10/31/2010"
- "token 11: 10/31/2010"
- "token 12: USD"
- "token 13: US"
- "token 14: USD"
- "token 15: 394234839"
- "token 16: 0"
- "token 17: CR-RW"

I haven't looked into the screen scraping code so I don't know where the spaces are added, but perhaps it's possible to use another delimiter?

**Comment by ciryon** [comment]
Update: It actually seems to work by replacing the split character to \t instead! I'll check some more, but initially that seems to do the trick.

Update2: Nope, need to do some tweaking since the order above doesn't seem to be what the program expects.

Update3: This seems to work for me:

http://gist.github.com/658755

**Comment by alanshutko** [comment]
I've had the same problem with the US store.  Applying ciryon's changes makes it work for me.  (Also Mac.)

**Comment by alanshutko** [comment]
I think the problem might be that there's a company name in company accounts, or is there a problem with apps with a space in the name?
