### ISSUE TITLE
not working with latest itunes connect report interface?

### ISSUE THREAD

**Issue by sobakasu** [alexvollmer/itunes-connect#2]
fetching has been failing for me for the last few days. apple has updated the itunes connect interface recently.

**Comment by alexvollmer** [comment]
I haven't been using his gem in awhile so I don't really keep it up to date. If you have a fix I'm happy to push a new release but I just don't have the bandwidth to maintain this project much anymore. 

Sorry for the lame answer.

--Alex

**Comment by sobakasu** [comment]
no probs.. using the power of github, i've forked it to http://github.com/2moro/itunes-connect - seems to be working again now.  i've had to change it from using httpclient to mechanize, i couldn't get it working with httpclient (some problem with setting cookies I think). will send you a pull request.
cheers, A
